// O2 deliberately lands before O3/O6 wire the result into manifest assembly (ONCELOCK.md §3.2).
#![allow(dead_code)]

use std::collections::VecDeque;

use pangs_api::GlobalId;
use pangs_pir::StatementCfg;

/// O2 result at statement-boundary granularity. `writable_after[p]` includes the writes
/// generated by the statement immediately following boundary `p` and every reachable successor.
pub(crate) struct Quiescence {
    writable_after: Vec<GlobalBits>,
    reachable: Vec<bool>,
}

impl Quiescence {
    pub(crate) fn compute(
        cfg: &StatementCfg,
        global_count: usize,
        generated_writes: &[Vec<GlobalId>],
    ) -> Result<Self, &'static str> {
        if cfg.boundaries.len() != generated_writes.len() {
            return Err("statement CFG and gen vector lengths differ");
        }
        for (index, boundary) in cfg.boundaries.iter().enumerate() {
            if boundary.id as usize != index {
                return Err("statement CFG boundary ids are not dense");
            }
            if boundary
                .successors
                .iter()
                .chain(&boundary.predecessors)
                .any(|edge| *edge as usize >= cfg.boundaries.len())
            {
                return Err("statement CFG edge is out of range");
            }
        }

        let generated = generated_writes
            .iter()
            .map(|writes| GlobalBits::from_globals(global_count, writes))
            .collect::<Vec<_>>();
        let mut writable_after = generated.clone();
        let mut queued = vec![true; cfg.boundaries.len()];
        let mut worklist = (0..cfg.boundaries.len()).rev().collect::<VecDeque<_>>();
        while let Some(boundary_id) = worklist.pop_front() {
            queued[boundary_id] = false;
            let boundary = &cfg.boundaries[boundary_id];
            let mut next = generated[boundary_id].clone();
            for &successor in &boundary.successors {
                next.union_with(&writable_after[successor as usize]);
            }
            if next != writable_after[boundary_id] {
                writable_after[boundary_id] = next;
                for &predecessor in &boundary.predecessors {
                    let predecessor = predecessor as usize;
                    if !queued[predecessor] {
                        queued[predecessor] = true;
                        worklist.push_back(predecessor);
                    }
                }
            }
        }

        let mut reachable = vec![false; cfg.boundaries.len()];
        let mut pending = vec![cfg.entry as usize];
        while let Some(boundary_id) = pending.pop() {
            let Some(slot) = reachable.get_mut(boundary_id) else {
                return Err("statement CFG entry is out of range");
            };
            if *slot {
                continue;
            }
            *slot = true;
            pending.extend(
                cfg.boundaries[boundary_id]
                    .successors
                    .iter()
                    .map(|successor| *successor as usize),
            );
        }

        Ok(Self {
            writable_after,
            reachable,
        })
    }

    pub(crate) fn is_quiescent(&self, boundary: u32, global: GlobalId) -> bool {
        self.reachable
            .get(boundary as usize)
            .copied()
            .unwrap_or(false)
            && !self.writable_after[boundary as usize].contains(global)
    }

    pub(crate) fn quiescent_boundaries(&self, global: GlobalId) -> Vec<u32> {
        self.reachable
            .iter()
            .enumerate()
            .filter_map(|(boundary, reachable)| {
                (*reachable && !self.writable_after[boundary].contains(global))
                    .then_some(boundary as u32)
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
struct GlobalBits(Vec<u64>);

impl GlobalBits {
    fn from_globals(global_count: usize, globals: &[GlobalId]) -> Self {
        let mut bits = Self(vec![0; global_count.div_ceil(64)]);
        for global in globals {
            let index = global.0 as usize;
            if index < global_count {
                bits.0[index / 64] |= 1_u64 << (index % 64);
            }
        }
        bits
    }

    fn union_with(&mut self, other: &Self) {
        for (slot, incoming) in self.0.iter_mut().zip(&other.0) {
            *slot |= incoming;
        }
    }

    fn contains(&self, global: GlobalId) -> bool {
        let index = global.0 as usize;
        self.0
            .get(index / 64)
            .is_some_and(|word| word & (1_u64 << (index % 64)) != 0)
    }
}

#[cfg(test)]
mod tests {
    use pangs_pir::{StatementBoundary, StatementCfg};

    use super::{GlobalId, Quiescence};

    fn boundary(id: u32, successors: &[u32], predecessors: &[u32]) -> StatementBoundary {
        StatementBoundary {
            id,
            block: id,
            ordinal: 0,
            loc: None,
            insertable: false,
            stmt_indices: Vec::new(),
            successors: successors.to_vec(),
            predecessors: predecessors.to_vec(),
        }
    }

    #[test]
    fn loop_write_quiesces_only_at_its_exit() {
        // entry -> loop; loop -> loop or exit
        let cfg = StatementCfg {
            entry: 0,
            boundaries: vec![
                boundary(0, &[1], &[]),
                boundary(1, &[1, 2], &[0, 1]),
                boundary(2, &[], &[1]),
            ],
            source_mapping_available: true,
        };
        let writes = vec![vec![], vec![GlobalId(0)], vec![]];
        let result = Quiescence::compute(&cfg, 2, &writes).unwrap();
        assert!(!result.is_quiescent(0, GlobalId(0)));
        assert!(!result.is_quiescent(1, GlobalId(0)));
        assert!(result.is_quiescent(2, GlobalId(0)));
        assert_eq!(result.quiescent_boundaries(GlobalId(0)), vec![2]);
        assert_eq!(result.quiescent_boundaries(GlobalId(1)), vec![0, 1, 2]);
    }

    #[test]
    fn branch_writes_union_at_the_merge_predecessor() {
        // entry branches to two arms; only the left writes; both merge at node 3.
        let cfg = StatementCfg {
            entry: 0,
            boundaries: vec![
                boundary(0, &[1, 2], &[]),
                boundary(1, &[3], &[0]),
                boundary(2, &[3], &[0]),
                boundary(3, &[], &[1, 2]),
            ],
            source_mapping_available: true,
        };
        let writes = vec![vec![], vec![GlobalId(0)], vec![], vec![]];
        let result = Quiescence::compute(&cfg, 1, &writes).unwrap();
        assert!(!result.is_quiescent(0, GlobalId(0)));
        assert!(!result.is_quiescent(1, GlobalId(0)));
        assert!(result.is_quiescent(2, GlobalId(0)));
        assert!(result.is_quiescent(3, GlobalId(0)));
    }

    #[test]
    fn omega_gen_poisons_every_global_before_the_unknown_call() {
        let cfg = StatementCfg {
            entry: 0,
            boundaries: vec![boundary(0, &[1], &[]), boundary(1, &[], &[0])],
            source_mapping_available: true,
        };
        let all_globals = vec![GlobalId(0), GlobalId(1), GlobalId(2)];
        let result = Quiescence::compute(&cfg, 3, &[all_globals, vec![]]).unwrap();
        for global in 0..3 {
            assert!(!result.is_quiescent(0, GlobalId(global)));
            assert!(result.is_quiescent(1, GlobalId(global)));
        }
    }
}
