[package]
name = "pangs-clients"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
jsonschema.workspace = true
pangs-api = { path = "../pangs-api" }
pangs-manifest = { path = "../pangs-manifest" }
pangs-pir = { path = "../pangs-pir" }
pangs-pag = { path = "../pangs-pag" }
pangs-solve = { path = "../pangs-solve" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true

[dev-dependencies]
tempfile.workspace = true
